In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('survey_results.csv')
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [4]:
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='str')

In [5]:
df.head()

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [6]:
df.tail()

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [7]:
df.sample(10)  #random values

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
31731,31732,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Oth...,Formal documentation provided by the owner of ...,...,1-2 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,60-120 minutes a day,Automated testing;Observability tools;Continuo...,Healthcare,Appropriate in length,Neither easy nor difficult,230000.0
43395,43396,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,I don’t code outside of work,Some college/university study without earning ...,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
46771,46772,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,...,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Observabilit...,Higher Education,Appropriate in length,Easy,99311.0
8733,8734,I agree,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
59548,59549,I agree,"I used to be a developer by profession, but no...",25-34 years old,"Not employed, but looking for work",NaN,NaN,"Associate degree (A.A., A.S., etc.)",Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
64792,64793,I agree,I am a developer by profession,45-54 years old,"Independent contractor, freelancer, or self-em...",Remote,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,74963.0
82795,82796,I agree,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",Remote,Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,23439.0
19054,19055,I agree,"I used to be a developer by profession, but no...",Under 18 years old,I prefer not to say,NaN,NaN,Something else,Online Courses or Certification;Other online r...,How-to videos;Video-based Online Courses;Stack...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
26135,26136,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Professional development or self-paced learnin...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Blogs with tips and tricks;Books;How-to videos...,...,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Continuous integ...,Healthcare,Appropriate in length,Easy,110000.0
84238,84239,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;On t...,How-to videos;Written Tutorials;Stack Overflow,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,115000.0

In [8]:
df.describe()

         ResponseId     CompTotal       WorkExp  ConvertedCompYearly
count  89184.000000  4.822500e+04  43579.000000         4.801900e+04
mean   44592.500000  1.036807e+42     11.405126         1.031101e+05
std    25745.347541  2.276847e+44      9.051989         6.814188e+05
min        1.000000  0.000000e+00      0.000000         1.000000e+00
25%    22296.750000  6.300000e+04      5.000000         4.390700e+04
50%    44592.500000  1.150000e+05      9.000000         7.496300e+04
75%    66888.250000  2.300000e+05     16.000000         1.216410e+05
max    89184.000000  5.000000e+46     50.000000         7.435143e+07

In [9]:
df.describe().map(lambda x:f'{x:.2f}')

,ResponseId,CompTotal,WorkExp,ConvertedCompYearly
count,89184.00,48225.00,43579.00,48019.00
mean,44592.50,1036806635562467391394372602402550216392704.00,11.41,103110.08
std,25745.35,227684720124393422298755801637800141977026560.00,9.05,681418.84
min,1.00,0.00,0.00,1.00
25%,22296.75,63000.00,5.00,43907.00
50%,44592.50,115000.00,9.00,74963.00
75%,66888.25,230000.00,16.00,121641.00
max,89184.00,4999999999999999205108735042797465575807673958...,50.00,74351432.00

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  str
 2   MainBranch                           89184 non-null  str
 3   Age                                  89184 non-null  str
 4   Employment                           87898 non-null  str
 5   RemoteWork                           73810 non-null  str
 6   CodingActivities                     73764 non-null  str
 7   EdLevel                              87973 non-null  str
 8   LearnCode                            87663 non-null  str
 9   LearnCodeOnline                      70084 non-null  str
 10  LearnCodeCoursesCert                 37076 non-null  str
 11  YearsCode                            87435 non-null  str
 12  YearsCodePro                         66136 non-null  str
 13  DevType                              76872 non-null  str
 14  OrgSize                              65043 non-null  str
 15  PurchaseInfluence                    64964 non-null  str
 16  TechList                             60851 non-null  str
 17  BuyNewTool                           83009 non-null  str
 18  Country                              87973 non-null  str
 19  Currency                             65334 non-null  str
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  str
 22  LanguageWantToWorkWith               80709 non-null  str
 23  DatabaseHaveWorkedWith               73435 non-null  str
 24  DatabaseWantToWorkWith               60911 non-null  str
 25  PlatformHaveWorkedWith               63628 non-null  str
 26  PlatformWantToWorkWith               51308 non-null  str
 27  WebframeHaveWorkedWith               66938 non-null  str
 28  WebframeWantToWorkWith               56741 non-null  str
 29  MiscTechHaveWorkedWith               57019 non-null  str
 30  MiscTechWantToWorkWith               46848 non-null  str
 31  ToolsTechHaveWorkedWith              77884 non-null  str
 32  ToolsTechWantToWorkWith              68315 non-null  str
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  str
 34  NEWCollabToolsWantToWorkWith         76649 non-null  str
 35  OpSysPersonal use                    86557 non-null  str
 36  OpSysProfessional use                78587 non-null  str
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  str
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  str
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  str
 40  OfficeStackSyncWantToWorkWith        69776 non-null  str
 41  AISearchHaveWorkedWith               56328 non-null  str
 42  AISearchWantToWorkWith               46150 non-null  str
 43  AIDevHaveWorkedWith                  25904 non-null  str
 44  AIDevWantToWorkWith                  19587 non-null  str
 45  NEWSOSites                           87973 non-null  str
 46  SOVisitFreq                          87140 non-null  str
 47  SOAccount                            87852 non-null  str
 48  SOPartFreq                           66061 non-null  str
 49  SOComm                               87692 non-null  str
 50  SOAI                                 47858 non-null  str
 51  AISelect                             87973 non-null  str
 52  AISent                               61501 non-null  str
 53  AIAcc                                38594 non-null  str
 54  AIBen                                61396 non-null  str
 55  AIToolInterested in Using            32783 non-null  str
 56  AIToolCurrently Using                36137 non-null  str
 57  AIToolNot interested in Using        21069 non-null  str
 58  AINextVery different                 12661 non-null  str
 59  AINextNeither different nor similar  6599 non-null   str
 60  AINextSomewhat similar               6238 non-null   str
 61  AINextVery similar                   2621 non-null   str
 62  AINextSomewhat different             23303 non-null  str
 63  TBranch                              65768 non-null  str
 64  ICorPM                               43668 non-null  str
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  str
 67  Knowledge_2                          41670 non-null  str
 68  Knowledge_3                          41798 non-null  str
 69  Knowledge_4                          41684 non-null  str
 70  Knowledge_5                          41527 non-null  str
 71  Knowledge_6                          41520 non-null  str
 72  Knowledge_7                          41467 non-null  str
 73  Knowledge_8                          41404 non-null  str
 74  Frequency_1                          41916 non-null  str
 75  Frequency_2                          41925 non-null  str
 76  Frequency_3                          41054 non-null  str
 77  TimeSearching                        42778 non-null  str
 78  TimeAnswering                        42629 non-null  str
 79  ProfessionalTech                     41783 non-null  str
 80  Industry                             36774 non-null  str
 81  SurveyLength                         86485 non-null  str
 82  SurveyEase                           86554 non-null  str
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), str(80)
memory usage: 57.2 MB

In [11]:
df = pd.read_csv('Data.tsv', delimiter='\t', index_col='Office')
df

,Name,Position,Age,Start date,Salary
Office,,,,,
Tokyo,Airi Satou,Accountant,33,2008-11-28,"$162,700"
London,Angelica Ramos,Chief Executive Officer (CEO),47,2009-10-09,"$1,200,000"
San Francisco,Ashton Cox,Junior Technical Author,66,2009-01-12,"$86,000"
London,Bradley Greer,Software Engineer,41,2012-10-13,"$132,000"
San Francisco,Brenden Wagner,Software Engineer,28,2011-06-07,"$206,850"
New York,Brielle Williamson,Integration Specialist,61,2012-12-02,"$372,000"
London,Bruno Nash,Software Engineer,38,2011-05-03,"$163,500"
New York,Caesar Vance,Pre-Sales Support,21,2011-12-12,"$106,450"
New York,Cara Stevens,Sales Assistant,46,2011-12-06,"$145,600"
Edinburgh,Cedric Kelly,Senior Javascript Developer,22,2012-03-29,"$433,060"
San Francisco,Charde Marshall,Regional Director,36,2008-10-16,"$470,600"
San Francisco,Colleen Hurst,Javascript Developer,39,2009-09-15,"$205,500"
Edinburgh,Dai Rios,Personnel Lead,35,2012-09-26,"$217,500"
New York,Donna Snider,Customer Support,27,2011-01-25,"$112,000"
Sydney,Doris Wilder,Sales Assistant,23,2010-09-20,"$85,600"
San Francisco,Finn Camacho,Support Engineer,47,2009-07-07,"$87,500"
San Francisco,Fiona Green,Chief Operating Officer (COO),48,2010-03-11,"$850,000"
Tokyo,Garrett Winters,Accountant,63,2011-07-25,"$170,750"
San Francisco,Gavin Cortez,Team Leader,22,2008-10-26,"$235,500"
Edinburgh,Gavin Joyce,Developer,42,2010-12-22,"$92,575"
New York,Gloria Little,Systems Administrator,59,2009-04-10,"$237,500"
London,Haley Kennedy,Senior Marketing Designer,43,2012-12-18,"$313,500"
London,Hermione Butler,Regional Director,47,2011-03-21,"$356,250"
San Francisco,Herrod Chandler,Sales Assistant,59,2012-08-06,"$137,500"
San Francisco,Hope Fuentes,Secretary,41,2010-02-12,"$109,850"
San Francisco,Howard Hatfield,Office Manager,51,2008-12-16,"$164,500"
New York,Jackson Bradshaw,Director,65,2008-09-26,"$645,750"
London,Jena Gaines,Office Manager,30,2008-12-19,"$90,560"
New York,Jenette Caldwell,Development Lead,30,2011-09-03,"$345,000"
Edinburgh,Jennifer Acosta,Junior Javascript Developer,43,2013-02-01,"$75,650"
Singapore,Jennifer Chang,Regional Director,28,2010-11-14,"$357,650"
San Francisco,Jonas Alexander,Developer,30,2010-07-14,"$86,500"
London,Lael Greer,Systems Administrator,21,2009-02-27,"$103,500"
Edinburgh,Martena Mccray,Post-Sales support,46,2011-03-09,"$324,050"
Singapore,Michael Bruce,Javascript Developer,29,2011-06-27,"$183,000"
London,Michael Silva,Marketing Designer,66,2012-11-27,"$198,500"
Sydney,Michelle House,Integration Specialist,37,2011-06-02,"$95,400"
Singapore,Olivia Liang,Support Engineer,64,2011-02-03,"$234,500"
New York,Paul Byrd,Chief Financial Officer (CFO),64,2010-06-09,"$725,000"
London,Prescott Bartlett,Technical Author,27,2011-05-07,"$145,000"
Edinburgh,Quinn Flynn,Support Lead,22,2013-03-03,"$342,000"
Tokyo,Rhona Davidson,Integration Specialist,55,2010-10-14,"$327,900"
Tokyo,Sakura Yamamoto,Support Engineer,37,2009-08-19,"$139,575"
Singapore,Serge Baldwin,Data Coordinator,64,2012-04-09,"$138,575"
Edinburgh,Shad Decker,Regional Director,51,2008-11-13,"$183,000"
Tokyo,Shou Itou,Regional Marketing,20,2011-08-14,"$163,000"
Edinburgh,Sonya Frost,Software Engineer,23,2008-12-13,"$103,600"
London,Suki Burks,Developer,53,2009-10-22,"$114,500"
London,Tatyana Fitzpatrick,Regional Director,19,2010-03-17,"$385,750"
New York,Thor Walton,Developer,61,2013-08-11,"$98,540"
Edinburgh,Tiger Nixon,System Architect,61,2011-04-25,"$320,800"
London,Timothy Mooney,Office Manager,37,2008-12-11,"$136,200"
San Francisco,Unity Butler,Marketing Designer,47,2009-12-09,"$85,675"
San Francisco,Vivian Harrell,Financial Controller,62,2009-02-14,"$452,500"
New York,Yuri Berry,Chief Marketing Officer (CMO),40,2009-06-25,"$675,000"
New York,Zenaida Frank,Software Engineer,63,2010-01-04,"$125,250"
San Francisco,Zorita Serrano,Software Engineer,56,2012-06-01,"$115,000"
Office,Name,Position,Age,Start date,Salary

In [12]:
df = pd.read_json('Employees_data.json')
df

,id,email,first_name,last_name,avatar
0,7,michael.lawson@reqres.in,Michael,Lawson,https://reqres.in/img/faces/7-image.jpg
1,8,lindsay.ferguson@reqres.in,Lindsay,Ferguson,https://reqres.in/img/faces/8-image.jpg
2,9,tobias.funke@reqres.in,Tobias,Funke,https://reqres.in/img/faces/9-image.jpg
3,10,byron.fields@reqres.in,Byron,Fields,https://reqres.in/img/faces/10-image.jpg
4,11,george.edwards@reqres.in,George,Edwards,https://reqres.in/img/faces/11-image.jpg
5,12,rachel.howell@reqres.in,Rachel,Howell,https://reqres.in/img/faces/12-image.jpg